version: 0.2

env:
  variables:
    PROWLER_FRAMEWORK: "cis_1.5_aws"
    FAIL_ON_FINDINGS: "false"
    OUTPUT_DIR: "output"
    DEMO_BUCKET_PREFIX: "thesis-demo-bucket"
    CONFIG_RULE_NAME: "thesis-s3-bucket-public-read-prohibited"   # your config rule name
    REMEDIATION_TIMEOUT_SECONDS: "180"    # how long to wait for remediation
    REMEDIATION_POLL_INTERVAL: "10"       # seconds between polls

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing Prowler..."
      - pip install --quiet prowler
      - pip install --quiet awscli # probably present already
  pre_build:
    commands:
      - echo "Preparing workspace..."
      - mkdir -p $OUTPUT_DIR
      - export TIMESTAMP=$(date +%Y%m%d_%H%M%S)
      - echo "timestamp=$TIMESTAMP" > $OUTPUT_DIR/build_metadata.txt

  build:
    commands:
      - echo "1) Run Prowler"
      - prowler aws --compliance "$PROWLER_FRAMEWORK" --output-formats json-asff csv html --output-directory "$OUTPUT_DIR" || true

      - echo "2) Create demo public bucket"
      - DEMO_BUCKET="${DEMO_BUCKET_PREFIX}-${TIMESTAMP}"
      - echo "demo bucket name: $DEMO_BUCKET"
      - aws s3api create-bucket --bucket $DEMO_BUCKET --create-bucket-configuration LocationConstraint=$(curl -s http://169.254.169.254/latest/meta-data/placement/region || echo eu-central-1) || true
      - aws s3api put-public-access-block --bucket $DEMO_BUCKET --public-access-block-configuration BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false
      - |
        cat > /tmp/public_policy.json <<POL
        {
          "Version":"2012-10-17",
          "Statement":[
            {
              "Sid":"AllowPublicRead",
              "Effect":"Allow",
              "Principal":"*",
              "Action":["s3:GetObject"],
              "Resource":["arn:aws:s3:::$DEMO_BUCKET/*"]
            }
          ]
        }
        POL
      - aws s3api put-bucket-policy --bucket $DEMO_BUCKET --policy file:///tmp/public_policy.json || true
      - echo "Bucket $DEMO_BUCKET set to public. Pause 5s"
      - sleep 5

      - echo "3) Trigger Config rule evaluation"
      - aws configservice start-config-rules-evaluation --config-rule-names $CONFIG_RULE_NAME || true

      - echo "4) Poll AWS Config for NON_COMPLIANT"
      - START=$(date +%s)
      - NON_COMPLIANT_FOUND=0
      - while [ $(( $(date +%s) - START )) -lt $REMEDIATION_TIMEOUT_SECONDS ]; do
          echo "Checking compliance for $DEMO_BUCKET";
          aws configservice get-compliance-details-by-config-rule --config-rule-name $CONFIG_RULE_NAME \
            --query "EvaluationResults[?EvaluationResultIdentifier.EvaluationResultQualifier.ResourceId=='$DEMO_BUCKET'].Compliance.ComplianceType" \
            --output text > /tmp/compliance_check.txt || true;
          STATUS=$(cat /tmp/compliance_check.txt | tr -d '\r\n' || echo "");
          echo "Status: '$STATUS'";
          if [ "$STATUS" = "NON_COMPLIANT" ]; then
            NON_COMPLIANT_FOUND=1;
            break;
          fi;
          sleep 5;
        done

      - if [ "$NON_COMPLIANT_FOUND" -ne 1 ]; then
          echo "ERROR: Could not find NON_COMPLIANT evaluation for $DEMO_BUCKET within timeout";
          echo "Saving debug logs...";
          aws configservice get-compliance-details-by-config-rule --config-rule-name $CONFIG_RULE_NAME --output json > $OUTPUT_DIR/config_rule_debug_${TIMESTAMP}.json || true;
          exit 2;
        fi

      - echo "5) Wait for remediation to occur (either automatic or manual trigger). Polling for COMPLIANT..."
      - START2=$(date +%s)
      - REMEDIED=0
      - while [ $(( $(date +%s) - START2 )) -lt $REMEDIATION_TIMEOUT_SECONDS ]; do
          echo "Checking if $DEMO_BUCKET became COMPLIANT";
          aws configservice get-compliance-details-by-config-rule --config-rule-name $CONFIG_RULE_NAME \
            --query "EvaluationResults[?EvaluationResultIdentifier.EvaluationResultQualifier.ResourceId=='$DEMO_BUCKET'].Compliance.ComplianceType" \
            --output text > /tmp/compliance_check2.txt || true;
          STATUS2=$(cat /tmp/compliance_check2.txt | tr -d '\r\n' || echo "");
          echo "Status2: '$STATUS2'";
          if [ "$STATUS2" = "COMPLIANT" ]; then
            REMEDIED=1;
            break;
          fi;
          sleep $REMEDIATION_POLL_INTERVAL;
        done

      - if [ "$REMEDIED" -ne 1 ]; then
          echo "ERROR: Remediation did not complete within timeout for $DEMO_BUCKET";
          aws configservice get-compliance-details-by-config-rule --config-rule-name $CONFIG_RULE_NAME --output json > $OUTPUT_DIR/config_remediation_failed_${TIMESTAMP}.json || true;
          # continue to cleanup but mark error
          REMEDIATION_FAILED=1
        else
          echo "Remediation successful for $DEMO_BUCKET"
          REMEDIATION_FAILED=0
        fi

      - echo "6) Capture results and logs"
      - aws s3api get-bucket-policy --bucket $DEMO_BUCKET --output json > $OUTPUT_DIR/${DEMO_BUCKET}_policy.json || true
      - aws s3api get-public-access-block --bucket $DEMO_BUCKET --output json > $OUTPUT_DIR/${DEMO_BUCKET}_pab.json || true
      - aws configservice get-compliance-details-by-config-rule --config-rule-name $CONFIG_RULE_NAME --output json > $OUTPUT_DIR/config_evaluations_${TIMESTAMP}.json || true

      - echo "7) Clean up demo bucket"
      - aws s3api delete-bucket-policy --bucket $DEMO_BUCKET || true
      - aws s3api put-public-access-block --bucket $DEMO_BUCKET --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true || true
      - aws s3 rb s3://$DEMO_BUCKET --force || true

      - if [ "$REMEDIATION_FAILED" -eq 1 ]; then
          echo "Failing the build due to remediation failure."
          exit 3;
        fi

  post_build:
    commands:
      - echo "Build finished, artifacts in $OUTPUT_DIR"
      - ls -la $OUTPUT_DIR

artifacts:
  files:
    - "**/*"
  base-directory: "output"
  discard-paths: no
